language: csharp
solution: Cottle.sln

matrix:
  include:
    - os: linux
      dist: trusty
      dotnet: 1.0.4
      mono: latest

install:
  - nuget restore Cottle.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory tests

script:
  - xbuild /p:Configuration=Release Cottle.sln
  - mono ./tests/NUnit.Console.3.0.1/tools/nunit3-console.exe ./Cottle.Test/bin/Release/Cottle.Test.dll
# - nuget pack -Prop Configuration=Release -Prop Platform=AnyCPU ./Cottle/Cottle.csproj
  - rm -fr ./artifacts
  - dotnet restore Cottle.dotnetcore.sln
  - dotnet build ./Cottle/Cottle.dotnetcore.csproj -c Release -f netstandard1.5
  - dotnet build ./Cottle.Test/Cottle.Test.dotnetcore.csproj -c Release -f netcoreapp1.1
  - dotnet test ./Cottle.Test/Cottle.Test.dotnetcore.csproj -c Release -f netcoreapp1.1
#  - dotnet pack ./Cottle/Cottle.dotnetcore.csproj -c Release -o ./artifacts
