language: csharp
solution: Cottle.sln

matrix:
  include:
    - os: linux
      dist: trusty
      dotnet: 2.0.0

script:
  - dotnet restore Cottle.sln
  - dotnet build ./Cottle/Cottle.csproj -c Release -f netstandard2.0
  - dotnet build ./Cottle.Test/Cottle.Test.csproj -c Release -f netcoreapp2.0
  - dotnet test ./Cottle.Test/Cottle.Test.csproj -c Release -f netcoreapp2.0
