language: csharp
solution: Cottle.sln

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 1.0.0-preview2-003121
      env: DOTNETCORE=1

install:
  - nuget restore Cottle.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory tests

script:
  - xbuild /p:Configuration=Release Cottle.sln
  - mono ./tests/NUnit.Console.3.0.1/tools/nunit3-console.exe ./Cottle.Test/bin/Release/Cottle.Test.dll
# - nuget pack -Prop Configuration=Release -Prop Platform=AnyCPU ./Cottle/Cottle.csproj
  - ./build_net_core.sh