using System;
using System.IO;
using Cottle.Settings;

namespace Cottle.Documents
{
    /// <summary>
    /// Dynamic document compiles template using MSIL generation for better
    /// performance. Code generated by JIT compiler can be reclaimed by garbage
    /// collector, but you should use a caching mechanism to avoid re-creating
    /// too many DynamicDocument instances using the same template source.
    /// </summary>
    public sealed class DynamicDocument : AbstractDocument
    {
        private readonly IDocument _document;

        [Obsolete("Use `Document.CreateNative(template, configuration).DocumentOrThrow` to get an equivalent document instance")]
        public DynamicDocument(TextReader reader, ISetting setting)
        {
            _document = Document.CreateNative(reader, AbstractDocument.CreateConfiguration(setting)).DocumentOrThrow;
        }

        [Obsolete("Use `Document.CreateNative(template).DocumentOrThrow` to get an equivalent document instance")]
        public DynamicDocument(TextReader reader) :
            this(reader, DefaultSetting.Instance)
        {
        }

        [Obsolete("Use `Document.CreateNative(template, configuration).DocumentOrThrow` to get an equivalent document instance")]
        public DynamicDocument(string template, ISetting setting) :
            this(new StringReader(template), setting)
        {
        }

        [Obsolete("Use `Document.CreateNative(template).DocumentOrThrow` to get an equivalent document instance")]
        public DynamicDocument(string template) :
            this(new StringReader(template), DefaultSetting.Instance)
        {
        }

        public override Value Render(IContext context, TextWriter writer)
        {
            return _document.Render(context, writer);
        }
    }
}