name: validate

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  DOTNET_VERSION: 6.0.x

jobs:
  check:
    name: Check code style
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet tool install -g dotnet-format
      - run: dotnet-format --check src/Cottle.sln

  build:
    name: Build for ${{ matrix.dotnet.framework }}
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        dotnet: # https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
          - framework: net5.0
          - framework: net6.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet build src/Cottle --framework ${{ matrix.dotnet.framework }}
      - run: dotnet build src/Cottle.Benchmark --framework ${{ matrix.dotnet.framework }}
      - run: dotnet build src/Cottle.Test --framework ${{ matrix.dotnet.framework }}

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet test src/Cottle.Test -f net6.0

  publish:
    name: Publish NuGet package
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet pack src/Cottle --configuration Release --output pack
      - run: dotnet nuget push ./pack/*.nupkg --no-symbols --skip-duplicate --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json"
 