name: Build, test & publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '40 4 * * *'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_VERSION: 7.0.x 

jobs:
  check:
    name: Check code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet format --no-restore --verify-no-changes src/Cottle.sln

  build:
    name: Build for ${{ matrix.dotnet.framework }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: # https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
          - framework: net5.0
          - framework: net6.0
          - framework: net7.0

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet build src/Cottle --framework ${{ matrix.dotnet.framework }}
      - run: dotnet build src/Cottle.Benchmark --framework ${{ matrix.dotnet.framework }}
      - run: dotnet build src/Cottle.Test --framework ${{ matrix.dotnet.framework }}

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet test src/Cottle.Test --framework net7.0

  publish:
    name: Publish NuGet package
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet pack src/Cottle --configuration Release --output pack
      - run: dotnet nuget push ./pack/*.nupkg --skip-duplicate --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json"
 
